theme: jekyll-theme-cayman
title: My Project Diary 
description: During the bioinformatics course KB8024 I will give dayly update on my progress.<br/> 
I have been tasked with making a 3 state secondary structure predictor.  
